#!/bin/bash
# Quick reference for running GRPO training

echo "=================================================="
echo "GRPO Training Quick Reference"
echo "=================================================="
echo ""
echo "📦 Files Available:"
echo "  • gpu_grpo_qwen3_0_6b.py  - GPU training (RECOMMENDED)"
echo "  • cpu_grpo_qwen3_0_6b.py  - CPU training (debug only)"
echo ""
echo "🚀 GPU Training (Recommended):"
echo "  python gpu_grpo_qwen3_0_6b.py"
echo ""
echo "  Features:"
echo "    ✓ CUDA GPU support (auto multi-GPU)"
echo "    ✓ bfloat16 precision"
echo "    ✓ Gradient checkpointing"
echo "    ✓ Batch size: 4, Grad accum: 2 (effective: 8)"
echo "    ✓ 100 samples, 3 epochs"
echo ""
echo "🐌 CPU Training (Debug Only):"
echo "  python cpu_grpo_qwen3_0_6b.py"
echo ""
echo "  Features:"
echo "    • CPU only (slow)"
echo "    • float32 precision"
echo "    • Batch size: 1"
echo "    • 10 samples, 2 epochs"
echo ""
echo "🎯 Select Specific GPU(s):"
echo "  CUDA_VISIBLE_DEVICES=7 python gpu_grpo_qwen3_0_6b.py"
echo "  CUDA_VISIBLE_DEVICES=0,7 python gpu_grpo_qwen3_0_6b.py"
echo ""
echo "📊 Monitor GPU Usage:"
echo "  watch -n 1 nvidia-smi"
echo "  # or"
echo "  nvtop"
echo ""
echo "📈 Expected Training Time:"
echo "  GPU: ~5-15 minutes (100 samples)"
echo "  CPU: ~10-30 minutes (10 samples only)"
echo ""
echo "💾 Output:"
echo "  Model: ./qwen-grpo-gpu-output/"
echo "  Logs:  ./qwen-grpo-gpu-output/grpo_metrics_*.csv"
echo ""
echo "=================================================="
